name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Timestamp
        run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.BIG_EVENT_WEBCODE_TOKEN4 }}

      - name: Build and tag image
        run: |
          docker build . --tag ghcr.io/siberianhusky10/geek-news-web:$TIMESTAMP
          docker tag ghcr.io/siberianhusky10/geek-news-web:$TIMESTAMP ghcr.io/siberianhusky10/geek-news-web:latest

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/siberianhusky10/geek-news-web:$TIMESTAMP
          docker push ghcr.io/siberianhusky10/geek-news-web:latest

#      - name: Restart web
#        run: |
#          docker compose -f /app/docker-compose.yaml up -d --force-recreate web